const CREATE_TODO = 'ADD_TODO'
const DELETE_TODO = 'DELETE_TODO'
const UPDATE_TODO_CONTENT = 'UPDATE_TODO'
const TOGGLE_TODO_COMPLETE = 'TOGGLE_TODO_COMPLETE'
const CHANGE_FILTER = 'CHANGE_FILTER'
const DELETE_ALL_TODO = 'DELETE_ALL_TODO'

export {
    CREATE_TODO,
    DELETE_TODO,
    UPDATE_TODO_CONTENT,
    TOGGLE_TODO_COMPLETE,
    CHANGE_FILTER,
    DELETE_ALL_TODO,
}