const GET_TODOS = 'GET_TODOS'
const CREATE_TODO = 'ADD_TODO'
const DELETE_TODO = 'DELETE_TODO'
const UPDATE_TODO_CONTENT = 'UPDATE_TODO'

export {
    GET_TODOS,
    CREATE_TODO,
    DELETE_TODO,
    UPDATE_TODO_CONTENT
}